config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  devise_for :users, controllers: { 
    confirmations: 'users/confirmations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

resources :users, only: [:index, :show]

  root to: 'static_page#landing_page'
  get  'static_page/policy'
  get 'profile', to: 'users#show', as: 'profile'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  unauthenticated do
    get  "home/index"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, 
         :confirmable, :trackable, 
         :omniauthable, omniauth_providers: [:google_oauth2]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!


    def after_sign_in_path_for(resource)
        user_path(resource)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/static_page_controller.rb
class StaticPageController < ApplicationController
  def landing_page
  end

  def policy
  end
end

app/controllers/users/confirmations_controller.rb
class ConfirmationsController < Devise::ConfirmationsController
    private
    def after_confirmation_path_for(resource_name, resource)
      sign_in(resource) # In case you want to sign in the user
      static_page_policy_path
    end
  end

app/controllers/users/omniauth_callbacks_controller.rb
# app/controllers/users/omniauth_callbacks_controller.rb:

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
    def google_oauth2
        # You need to implement the method below in your model (e.g. app/models/user.rb)
        @user = User.from_omniauth(request.env['omniauth.auth'])
  
        if @user.persisted?
          flash[:notice] = I18n.t 'devise.omniauth_callbacks.success', kind: 'Google'
          sign_in_and_redirect @user, event: :authentication
        else
          session['devise.google_data'] = request.env['omniauth.auth'].except('extra') # Removing extra as it can overflow some session stores
          redirect_to new_user_registration_url, alert: @user.errors.full_messages.join("\n")
        end
    end
  end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def index
        @users = User.all
    end

    def show
        @user = User.find(params[:id])
    end
    
    

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/static_page_helper.rb
module StaticPageHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/_breadcrum.html.erb
<nav aria-label="breadcrumb bg-dark">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="#">Home</a></li>
    <li class="breadcrumb-item"><a href="#">Library</a></li>
    <li class="breadcrumb-item active" aria-current="page">Data</li>
  </ol>
</nav>

app/views/layouts/_header.html.erb
<%= render "layouts/navbar" %>
<%= render "layouts/messages" %>

app/views/layouts/_messages.html.erb
<% if notice.present? %>
    <div class="alert alert-success" role="alert">
        <p class="notice"><%= notice %></p>
    </div>
<% end %>
<% if alert.present? %>
    <div class="alert alert-danger" role="alert">
        <p class="alert"><%= alert %></p>
    </div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-md navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="<%= root_path %>"><i class="bi bi-toggle-on"> </i> SchoolTrack</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="<%= root_path %>"></i>Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%= static_page_policy_path %>">Policy</a>
        </li>
        <li class="nav-item dropdown">
        <% if current_user %>
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
          <i class="bi bi-person"></i> <%= current_user.email %>
          </a>
        <% end %>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="<%= edit_user_registration_path %>">Settings</a></li>
            <li>< %= link_to 'Logout', destroy_user_session_path, method: :delete, class: "dropdown-item" %> </li>
            <li><%= link_to 'Profile', (current_user ? user_path(current_user) : profile_path),  class: "dropdown-item" %> </li>
           
          </ul>
        </li>
      </ul>
      <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3" role="search">
          <input type="search" class="form-control form-control-dark text-bg-dark" placeholder="Search..." aria-label="Search">
        </form>
    <% if !current_user %>
        <div class="text-end">
           
          <a href="<%= new_user_session_path %>" class="btn btn-dark">Signin</a>
          <a href="<%= new_user_registration_path %>" class="btn btn-success">Signup</a>
        
    <% end %>

        </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SchoolTrack</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
  <%= render "layouts/header" %>
  <br>
    <div class="container"><%= yield %></div>
  <%= render "layouts/footer" %>
  </body>
</html>

app/views/static_page/landing_page.html.erb
<div class="container">
  <h1>Landing::Page</h1>
  <i>...loading root page</i>
</div>   

app/views/static_page/policy.html.erb
<div class="container">
<h1>StaticPage#policy</h1>
<p>Find me in app/views/static_page/policy.html.erb</p>

</div>

app/views/users/index.html.erb
<h3>Index:Users</h3>

<% @users.each do |user| %>
    Email: <%= user.email %><br>
  <% end %>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<h3>Showing user :: <%= @user.email %> </h3>


<ul class="list-group list-group-flush">
        <li class="list-group-item">ID: <%= @user.id %></li>
        <li class="list-group-item">Email: <%= @user.email%></li>
        <li class="list-group-item">Created: at <%= @user.created_at%></li>
        <li class="list-group-item">Updated at: <%= @user.updated_at%></li>
        <li class="list-group-item">User object: <%= @user%></li>
    
</ul>


<h4>User Trackable info... </h4>
<ul>
<li class=" " >User sign count: <%= @user.sign_in_count %> </li>
<li class=" " >User sign current at: <%= @user.current_sign_in_at %>  </li>
<li class=" " >User signlast at: <%= @user.last_sign_in_at %> </li>
<li class=" " >User sign ip: <%= @user.current_sign_in_ip %> </li>
<li class=" " >User last sign <ip></ip>: <%= @user.last_sign_in_ip %> </li>
</ul>